-- gasout 스키마 (Supabase에서 이전, 2026-07-06)
-- 제외: RLS 정책, auth 스키마 참조, _migrations 테이블

CREATE TABLE power_plants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  capacity_mw integer,
  status text CHECK (status IN ('계획중', '건설중', '운영중', '백지화')),
  operator text,
  permit_date date,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  classification varchar,
  plant_unit varchar,
  commissioning_date varchar,
  fuel_type varchar,
  notes text,
  info_link text,
  plant_type varchar,
  plant_format varchar,
  unit_count integer,
  unit_capacity varchar,
  boiler_manufacturer varchar,
  turbine_manufacturer varchar,
  generator_manufacturer varchar,
  rated_voltage varchar,
  usage_type varchar,
  member_type varchar,
  market_type varchar,
  dispatch_type varchar
);

-- profiles: Supabase에서는 auth.users FK였으나 Neon에서는 독립 테이블 (참고용 보존)
CREATE TABLE profiles (
  id uuid PRIMARY KEY,
  role text DEFAULT 'activist' CHECK (role IN ('admin', 'activist')),
  managed_region_id uuid,
  created_at timestamptz DEFAULT now(),
  email text,
  full_name text,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE activity_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plant_id uuid REFERENCES power_plants(id),
  author_id uuid REFERENCES profiles(id),
  title text NOT NULL,
  content text NOT NULL,
  images text[],
  youtube_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  title text,
  url text UNIQUE,
  source text,
  published_at timestamptz,
  summary text,
  content text,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  location_type text DEFAULT 'national' CHECK (location_type IN ('national', 'regional', 'power_plant')),
  address_full text,
  si_do text,
  si_gun_gu text,
  eup_myeon_dong text,
  latitude numeric,
  longitude numeric,
  power_plant_id uuid REFERENCES power_plants(id),
  updated_at timestamptz DEFAULT now(),
  ai_score integer,
  is_relevant boolean,
  ai_summary text,
  ai_analyzed_at timestamptz,
  ai_model_version varchar,
  tags text[]
);

CREATE INDEX idx_articles_status_published ON articles (status, published_at DESC);

CREATE TABLE gas_plants (
  id text PRIMARY KEY,
  type text NOT NULL CHECK (type IN ('복합발전', '열병합발전')),
  owner text NOT NULL,
  plant_name text NOT NULL,
  unit_number real,
  location text,
  capacity_mw real NOT NULL,
  status text CHECK (status IN ('운영', '건설', '계획')),
  operation_start text,
  closure_planned text,
  note text,
  latitude real,
  longitude real,
  geocoded boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE gas_terminals (
  id text PRIMARY KEY,
  type text NOT NULL DEFAULT 'LNG터미널',
  category text CHECK (category IN ('가스공사', '민간')),
  owner text NOT NULL,
  terminal_name text NOT NULL,
  tank_number real,
  location text,
  capacity_kl real,
  capacity_mtpa real,
  status text CHECK (status IN ('운영', '건설', '계획')),
  operation_start text,
  closure_planned text,
  latitude real,
  longitude real,
  geocoded boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE climate_test_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id varchar NOT NULL UNIQUE,
  result_type varchar NOT NULL,
  answers jsonb NOT NULL,
  utm_source varchar,
  utm_medium varchar,
  utm_campaign varchar,
  created_at timestamptz DEFAULT now(),
  completed_at timestamptz DEFAULT now(),
  shared boolean DEFAULT false
);

CREATE TABLE climate_declarations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  test_response_id uuid REFERENCES climate_test_responses(id),
  session_id varchar,
  name varchar NOT NULL,
  email varchar,
  region varchar,
  phone varchar,
  consent_privacy boolean NOT NULL,
  consent_marketing boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  result_type varchar
);
